### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by pisia228** [PushpenderIndia/technowlogger#29]
![error](https://user-images.githubusercontent.com/73673945/99450044-e3127380-2928-11eb-9239-fb61f6531ffd.jpg)
when i try to run script i get this error.

**Comment by fluorek** [comment]
I have the same

**Comment by PushpenderIndia** [comment]
Use debug flag while compiling, run the exe using command prompt, so that
you get the proper error

Note the error and send it here, in most of the case there is some missing
dependencies on your system which leads to this error,

If you get any error like "ModuleNotFound", then try installing it and
create a fresh payload
