### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by Spl01ter** [PushpenderIndia/technowlogger#31]
"Generated Payload is Encryted with base64, hence makes extremely difficult to reverse engineer the payload"
base64 encoded, not encrypted. Base64 can very easily be decoded and therefore reverse engineered. The hard part about reverse engineering would be reverse engineering would be uncompiling the executable.

**Comment by PushpenderIndia** [comment]
Yeah I know Base64 is not a encryption, the correct word should be
Obfuscation, as it becomes very hard to find the hardcoded email through
static malware analysis

As the payload is just the base64 encoded string which will be decoded and
executed in the run time,

Otherwise, we can easily find all the strings used in the program using
debugging software such as ollydbg, etc

Thats why most of the people also try to store things like this:

a = "pas"
b = a+"sw"
cas = b+ "ord"

And the cas variable will have the "password" String,

Through there are some techniques by which we can find the hardcoded email
and password by tricking the virus by making self signed gmail certificate,

But these are some application level things which I have implement to avoid
reverse engineering
